# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: condition.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'condition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ondition.proto\"d\n\tCondition\x12\x1a\n\x03\x63\x61r\x18\x01 \x01(\x0b\x32\r.CarCondition\x12\x1f\n\x06orders\x18\x02 \x03(\x0b\x32\x0f.OrderCondition\x12\x1a\n\x05limit\x18\x03 \x01(\x0b\x32\x0b.Limitation\"x\n\x0c\x43\x61rCondition\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x17\n\x08original\x18\x02 \x01(\x0b\x32\x05.Size\x12\x16\n\x07reserve\x18\x03 \x01(\x0b\x32\x05.Size\x12\x14\n\x05\x66rame\x18\x04 \x01(\x0b\x32\x05.Size\x12\x13\n\x04head\x18\x05 \x01(\x0b\x32\x05.Size\"\'\n\x04Size\x12\t\n\x01L\x18\x01 \x01(\x02\x12\t\n\x01W\x18\x02 \x01(\x02\x12\t\n\x01H\x18\x03 \x01(\x02\"?\n\x0eOrderCondition\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x1c\n\x05\x62oxes\x18\x02 \x03(\x0b\x32\r.BoxCondition\"\x96\x01\n\x0c\x42oxCondition\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x17\n\x08original\x18\x02 \x01(\x0b\x32\x05.Size\x12\x16\n\x07reserve\x18\x03 \x01(\x0b\x32\x05.Size\x12\x13\n\x04grip\x18\x04 \x01(\x0b\x32\x05.Grip\x12\n\n\x02Nt\x18\x05 \x01(\x05\x12\x12\n\ncontractId\x18\x06 \x01(\t\x12\x12\n\nmaterialId\x18\x07 \x01(\t\"*\n\x04Grip\x12\n\n\x02P1\x18\x01 \x03(\x05\x12\n\n\x02P2\x18\x02 \x03(\x05\x12\n\n\x02P3\x18\x03 \x03(\x05\"\xba\x01\n\nLimitation\x12\r\n\x05N1min\x18\x01 \x01(\x05\x12\r\n\x05T3max\x18\x02 \x01(\x05\x12\r\n\x05N2max\x18\x03 \x01(\x05\x12\x0e\n\x06T12min\x18\x04 \x01(\x05\x12\x0c\n\x04\x45lim\x18\x05 \x03(\x05\x12\x13\n\x0bIstrapezoid\x18\x06 \x01(\x08\x12\x10\n\x08Strategy\x18\x07 \x01(\x05\x12\x0f\n\x07P1P2gap\x18\x08 \x01(\x05\x12\t\n\x01G\x18\t \x01(\x05\x12\r\n\x05Tback\x18\n \x01(\x05\x12\x0f\n\x07Overlap\x18\x0b \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'condition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONDITION']._serialized_start=19
  _globals['_CONDITION']._serialized_end=119
  _globals['_CARCONDITION']._serialized_start=121
  _globals['_CARCONDITION']._serialized_end=241
  _globals['_SIZE']._serialized_start=243
  _globals['_SIZE']._serialized_end=282
  _globals['_ORDERCONDITION']._serialized_start=284
  _globals['_ORDERCONDITION']._serialized_end=347
  _globals['_BOXCONDITION']._serialized_start=350
  _globals['_BOXCONDITION']._serialized_end=500
  _globals['_GRIP']._serialized_start=502
  _globals['_GRIP']._serialized_end=544
  _globals['_LIMITATION']._serialized_start=547
  _globals['_LIMITATION']._serialized_end=733
# @@protoc_insertion_point(module_scope)
