# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: issuer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'issuer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_pkg.interface import answer_pb2 as answer__pb2
from grpc_pkg.interface import condition_pb2 as condition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cissuer.proto\x1a\x0c\x61nswer.proto\x1a\x0f\x63ondition.proto\"F\n\x0cIssueRequest\x12\x1d\n\tcondition\x18\x01 \x01(\x0b\x32\n.Condition\x12\x17\n\x06\x61nswer\x18\x02 \x01(\x0b\x32\x07.Answer\"-\n\nIssueReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2/\n\x06Issuer\x12%\n\x05Issue\x12\r.IssueRequest\x1a\x0b.IssueReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'issuer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISSUEREQUEST']._serialized_start=47
  _globals['_ISSUEREQUEST']._serialized_end=117
  _globals['_ISSUEREPLY']._serialized_start=119
  _globals['_ISSUEREPLY']._serialized_end=164
  _globals['_ISSUER']._serialized_start=166
  _globals['_ISSUER']._serialized_end=213
# @@protoc_insertion_point(module_scope)
