syntax = "proto3";

// 求解结果总包
message Answer{
    repeated Block blocks = 1; // 堆垛队列
    Index index = 2; // 全局统计参数
    SpecialInd SpecialInd = 3; // P1P3来料特殊翻转信息
}

// 堆垛信息(同一堆垛中仅包含一种垛型，其余两种队列为空)
message Block{
    int32 queueId = 1; // 队列中序号
    string orderId = 2; // 对应子订单号
    repeated Regular regular = 3; // 规整垛
    repeated Mixture mixture = 4; // 混装面
    repeated Trapezoid trapezoid = 5; // 梯形尾垛
    repeated Info blockInfo = 6; // 垛型信息
}

// 规整垛
message Regular{
    int32 N1 = 1; // P1每行个数
    int32 N2 = 2; // P2每行个数
    int32 N3 = 3; // P3每行个数
    int32 T12 = 4; // P1P2高度行数
    int32 T3 = 5; // P3高度行数
    int32 F13 = 6; // P1P3面数
    int32 F2 = 7; // P2面数
    int32 E = 8; // 尾料堆放形式(0 无，1 P1前置，2 P3顶置)
    int32 Nx = 9; // 尾料个数
    repeated Stack Stack = 10; // 堆叠缝隙排布
    repeated Group Group = 11; // 堆叠按爪分组
    string Type = 12; // 箱型代号
}

// 混装面
message Mixture{
    repeated MixtureItem Items = 1; //混裝面信息列表
}

// 混裝面信息列表
message MixtureItem{
   string Type = 1; //箱型代号
   int32 Num = 2; //箱子数量
   Position Pos = 3; //放置位置
}

// 混裝面每抓位置
message Position{
   float X = 1; //沿车厢深度方向
   float Y = 2; //沿车厢宽度方向
   float Z = 3; //沿车厢高度方向
}

// 梯形尾垛(面数固定为1，下方P1堆放，上方P3堆放，如有尾料以P3顶置形式堆放)
message Trapezoid{
    int32 N1 = 1; // P1每行个数
    int32 N3 = 2; // P3每行个数
    int32 T1 = 3; // P1高度行数
    int32 T3 = 4; // P3高度行数
    int32 Nx = 5; // 尾料个数
    repeated Stack Stack = 6; // 堆叠缝隙排布
    repeated Group Group = 7; // 堆叠按爪分组
    bool Isdoor = 8; // 是否需要尾门变形
    string Type = 9; // 箱型代号
}

// 堆叠缝隙排布
message Stack{
    repeated int32 Width = 1; // 从左至右每个箱体与箱体或墙面间的缝隙宽度，百分比表示，仅表示P1P2整行
}

// 堆叠按爪分组
message Group{
    repeated int32 Unit = 1; // 从左至右每爪箱体数量分组，仅表示行内所有P1箱体
}

message Info {
    string orderId = 1; // 出库单地址
    string contractId = 2; // 合同号
    string materialId = 3; // 物料代号
    string type = 4; // 箱型代号
    int32 Nt = 5; // 箱型数量
}

// 全局统计参数(暂定)
message Index{
    int32 Ns = 1; // 整车总箱数
    float Us = 2; // 整车总空间装载率
    float Um = 3; // 总外接长方体装载率
    repeated int32 Gn = 4; // P1P2P3总抓数
    float Tp = 5; // 预估总码垛时长
}

// P1P3来料特殊翻转信息(PLC通知用)
message SpecialInd{
    int32 Nt = 1; // 整车总箱数
    repeated string BoxType = 2; // 全车垛型箱型顺序
    repeated int32 BoxNum = 3; // 全车垛型各箱型个数
    int32 BoxP3Sum = 4; // P3不翻转总数
    repeated int32 BoxP3IndNum = 5; // 各垛P3不翻转个数
    repeated int32 BoxP3Ind = 6; // P3不翻转序号
    int32 BoxRightSum = 7; // P1右翻总数
    repeated int32 BoxRightNum = 8; // 各垛P1右翻个数
    repeated int32 BoxRightInd = 9; // P1右翻序号
}
