syntax = "proto3";

message Size{
    float L = 1;
    float W = 2;
    float H = 3;
}

message Grip{
    repeated int32 P1 = 1;
    repeated int32 P2 = 2;
    repeated int32 P3 = 3;
}

message CarCondition{
    string type = 1;
    Size original = 2;
    Size reserve = 3;
    Size frame = 4;
}

message BoxCondition{
    string type = 1;
    Size original = 2;
    Size reserve = 3;
    Grip grip = 4;
    int32 Nt = 5;
}

message Limitation{
    int32 N1min = 1;
    int32 T3max = 2;
    int32 N2max = 3;
    int32 T12min = 4;
    repeated int32 Elim = 5;
    bool Istrapezoid = 6;
    int32 Strategy = 7;
    int32 P1P2gap = 8;
    int32 G = 9;
    int32 Tback = 10;
    repeated int32 Overlap = 11;
}

message Condition{
    CarCondition car = 1;
    repeated BoxCondition boxes = 2;
    Limitation limit = 3;
}

message Regular{
    int32 N1 = 1;
    int32 N2 = 2;
    int32 N3 = 3;
    int32 T12 = 4;
    int32 T3 = 5;
    int32 F13 = 6;
    int32 F2 = 7;
    int32 E = 8;
    int32 Nx = 9;
    repeated Stack Stack = 10;
    repeated Group Group = 11;
    string type = 12;
}

message Mixture{
    repeated MixtureItem Items = 1;
}

message MixtureItem{
    string Type = 1;
    int32 Num = 2;
    Position Pos = 3;
}

message Position{
    float X = 1; // 沿车厢深度方向
    float Y = 2; // 沿车厢宽度方向
    float Z = 3; // 沿车厢高度方向
}

message Trapezoid{
    int32 N1 = 1;
    int32 N3 = 2;
    int32 T1 = 3;
    int32 T3 = 4;
    int32 Nx = 5;
    repeated Stack Stack = 6;
    repeated Group Group = 7;
    bool Isdoor = 8;
    string type = 9;
}

message Stack{
    repeated int32 Width = 1;
}

message Group{
    repeated int32 Unit = 1;
}

message Index{
    int32 Ns = 1;
    float Us = 2;
    float Um = 3;
    repeated int32 Gn = 4;
    float Tp = 5;
}

message Answer{
    repeated Regular regular = 1;
    repeated Mixture mixture = 2;
    repeated Trapezoid trapezoid = 3;
}


service Issuer {
  rpc Issue (IssueRequest) returns (IssueReply) {}
}

message IssueRequest {
    Condition condition = 1;
    Answer answer = 2;
}

message IssueReply {
    bool result = 1;
    string message = 2;
}

